USE `db_teste_serasa`;

ALTER TABLE transacaotransporte ADD INDEX IDX_TRANSACAOTRANSPORTE_CHECK_EXISTENTE (
    placa_caminhao,
    id_grao,
    data_hora_retorno
);

ALTER TABLE transacaotransporte
DROP FOREIGN KEY FK_TRANSACAOTRANSPORTE_PESAGEM,
DROP FOREIGN KEY FK_TRANSACAOTRANSPORTE_CAMINHAO,
DROP FOREIGN KEY FK_TRANSACAOTRANSPORTE_TIPO_GRAO;

ALTER TABLE transacaotransporte
    ADD CONSTRAINT FK_TRANSACAOTRANSPORTE_PESAGEM
        FOREIGN KEY (id_pesagem)
            REFERENCES pesagens (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
ADD CONSTRAINT FK_TRANSACAOTRANSPORTE_CAMINHAO
    FOREIGN KEY (placa_caminhao)
    REFERENCES caminhao (placa)
    ON UPDATE CASCADE
       ON DELETE CASCADE,
ADD CONSTRAINT FK_TRANSACAOTRANSPORTE_TIPO_GRAO
    FOREIGN KEY (id_grao)
    REFERENCES tipograo (id)
    ON UPDATE CASCADE
       ON DELETE CASCADE;