USE `db_teste_serasa`;

ALTER TABLE pesagens
DROP FOREIGN KEY FK_PESAGENS_CAMINHAO,
DROP FOREIGN KEY FK_PESAGENS_TIPO_GRAO,
DROP FOREIGN KEY FK_PESAGENS_BALANCA;

ALTER TABLE pesagens
    ADD CONSTRAINT FK_PESAGENS_CAMINHAO
        FOREIGN KEY (placa)
            REFERENCES caminhao (placa)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
ADD CONSTRAINT FK_PESAGENS_TIPO_GRAO
    FOREIGN KEY (id_tipo_grao)
    REFERENCES tipograo (id)
    ON UPDATE CASCADE
       ON DELETE CASCADE,
ADD CONSTRAINT FK_PESAGENS_BALANCA
    FOREIGN KEY (id_balanca)
    REFERENCES balanca (id)
    ON UPDATE CASCADE
       ON DELETE CASCADE;

ALTER TABLE balanca
DROP FOREIGN KEY FK_BALANCA_ID_FILIAL;

ALTER TABLE balanca
    ADD CONSTRAINT FK_BALANCA_ID_FILIAL
        FOREIGN KEY (id_filial)
            REFERENCES filial (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE;